=== ACampbellWashburn/gadgetron/apps/gadgetron/schema/gadgetron.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://gadgetron.sf.net/gadgetron" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gadgetron.sf.net/gadgetron">

    <!--
    Gadgetron configuration xml includes two elements: port and workingdirectory
    The 'port' is where gadgetron is listening to. This 'workingdirectory' is 
    the directory which gadgetron uses to store the temporary files, 
    e.g. the dependency measurements. If 'workingdirectory' is not set, the default
    directory will be used ('/tmp/gadgetron' in linux and 'c:/temp/gadgetron' in windows).
    -->

    <xs:element name="gadgetronConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="port" type="xs:string"/>
                <xs:element maxOccurs="1" minOccurs="0" name="workingdirectory" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

  <xs:element name="gadgetronStreamConfiguration">
    <xs:complexType>
      <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reader">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element name="slot" type="xs:unsignedShort"/>
                              <xs:element name="dll" type="xs:string"/>
                              <xs:element name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="writer">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1" name="slot" type="xs:unsignedShort"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="gadget">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1"  name="name" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                                  <xs:complexType>
                                      <xs:sequence>
                                          <xs:element maxOccurs="1" minOccurs="1" name="name" type="xs:string"/>
                                          <xs:element maxOccurs="1" minOccurs="1" name="value" type="xs:string"/>
                                      </xs:sequence>        
                                  </xs:complexType>
                              </xs:element>
                             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ACampbellWashburn/gadgetron/gadgets/radial/radial_single.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_core</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>NoiseAdjust</name>
      <dll>gadgetron_mricore</dll>
      <classname>MRINoiseAdjustGadget</classname>
    </gadget>

    <gadget>
      <name>RemoveROOversampling</name>
      <dll>gadgetron_core</dll>
      <classname>RemoveROOversamplingGadget</classname>
    </gadget>

   <gadget>
      <name>PCA</name>
      <dll>gadgetron_mricore</dll>
      <classname>PCACoilGadget</classname>
    </gadget>

    <gadget>
      <name>CoilReduction</name>
      <dll>gadgetron_core</dll>
      <classname>CoilReductionGadget</classname>
      <property>
        <name>coils_out</name>
        <value>8</value>
      </property>
    </gadget>

    <gadget>
      <name>GPUCGRadial0</name>
      <dll>gadgetron_gpusense</dll>
      <classname>GPUCGGoldenRadialGadget</classname>
      <property><name>deviceno</name>                <value>0</value></property>
      <property><name>sliceno</name>                 <value>0</value></property>
      <property><name>profiles_per_frame</name>      <value>32</value></property>
      <property><name>shared_profiles</name>         <value>0</value></property>
      <property><name>number_of_iterations</name>    <value>10</value></property>
      <property><name>cg_limit</name>                <value>1e-6</value></property>
      <property><name>oversampling</name>            <value>1.25</value></property>
      <property><name>kernel_width</name>            <value>5.5</value></property>
      <property><name>kappa</name>                   <value>0.3</value></property>
      <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    </gadget>

     <gadget>
      <name>Extract</name>
      <dll>gadgetron_core</dll>
      <classname>ExtractGadget</classname>
    </gadget>

	<!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_core</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_core</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>


    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_core</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>

    <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetron_core</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/grappa/config/grappa_unoptimized.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
     <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
  
    <gadget>
      <name>RemoveROOversampling</name>
      <dll>gadgetron_mricore</dll>
      <classname>RemoveROOversamplingGadget</classname>
    </gadget>

    <gadget>
      <name>Grappa</name>
      <dll>gadgetron_grappa</dll>
      <classname>GrappaGadget</classname>
      <property><name>target_coils</name><value>8</value></property>
    </gadget>

    <gadget>
      <name>GrappaUnmixing</name>
      <dll>gadgetron_grappa</dll>
      <classname>GrappaUnmixingGadget</classname>
    </gadget>

     <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_mricore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>
    
    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_mricore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
 
    <!--
    <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetCPLX</classname>
    </gadget>
    -->

    <!--    
    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>
    -->

    <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/toolboxes/gtplus/config/GadgetronProgram_gtPlus_2DT_Cartesian_CloudNode.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- 
        GT Plus configuratin file for 2DT cartesian reconstruction on GtPlus Cloud
        This configuration file configures one gadget to perform the reconstruction for
        2DT job packages

        Depending on the incoming algorithm parameters, both linear and non-linear reconstruction
        can be performed

        Author: Hui Xue
        Magnetic Resonance Technology Program
        National Heart, Lung and Blood Institute
        National Institutes of Health
        10 Center Drive, Bethesda
        MD 20814
        USA
        Email: hui.xue@nih.gov
    -->

    <!-- reader -->
    <reader>
        <slot>1013</slot>
        <dll>gadgetronPlus</dll>
        <classname>GtPlusCloudJobMessageReaderCPFL</classname>
    </reader>

    <!-- writer -->
    <writer>
        <slot>1013</slot>
        <dll>gadgetronPlus</dll>
        <classname>GtPlusCloudJobMessageWriterCPFL</classname>
    </writer>

    <!--
    Recon computation for 2DT/3DT cases, process one job
    a gtPlusReconJob2DT job consists of kspace, kernel and parameters
    kspace: [RO E1 CHA E2/PHS]
    -->

    <gadget>
        <name>Recon</name>
        <dll>gadgetronPlus</dll>
        <classname>GtPlusReconJob2DTGadget</classname>

        <!-- parameters for debug and timing -->
        <property>
            <name>debugFolder</name>
            <value></value>
        </property>

        <property>
            <name>performTiming</name>
            <value>true</value>
        </property>

        <property>
            <name>verboseMode</name>
            <value>false</value>
        </property>

    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/spiral/spiral.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         

    <reader>
      <slot>1001</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIAcquisitionReader</classname>
    </reader>

    <writer>
      <slot>1004</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>SpiralGadget</name>
      <dll>gadgetronspiral</dll>
      <classname>SpiralGadget</classname>
    </gadget>
    <gadget>
      <name>Extract</name>
      <dll>gadgetroncore</dll>
      <classname>ExtractGadget</classname>
      <!--
      <property><name>extract_mask</name><value>9</value></property>
      -->
    </gadget>

	<!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetroncore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->
    
    
    <gadget>
      <name>AutoScaleGadget</name>
      <dll>gadgetroncore</dll>
      <classname>AutoScaleGadget</classname>
   </gadget> 

   <gadget>
      <name>FloatToShort</name>
      <dll>gadgetroncore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
 
 	<!--
    <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetCPLX</classname>
    </gadget>
    -->
    
    <gadget>
      <name>ImageFinishShort</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>
    
 	<!--
    <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>
    -->

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/epi/epi.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
  
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
  
    <gadget>
      <name>NoiseAdjust</name>
      <dll>gadgetron_mricore</dll>
      <classname>NoiseAdjustGadget</classname>
    </gadget>

    <gadget>
      <name>ReconX</name>
      <dll>gadgetron_epi</dll>
      <classname>EPIReconXGadget</classname>
    </gadget>

    <gadget>
      <name>Acc</name>
      <dll>gadgetron_mricore</dll>
      <classname>AccumulatorGadget</classname>
    </gadget>

    <gadget>
      <name>FFTYZ</name>
      <dll>gadgetron_epi</dll>
      <classname>FFTYZGadget</classname>
    </gadget>

   <gadget>
      <name>CoilCombinePython</name>
      <dll>gadgetron_python</dll>
      <classname>ImagePythonGadget</classname>
      <property><name>python_path</name>                  <value>/home/myuser/scripts/python</value></property>
      <property><name>python_module</name>                <value>rms_coil_combine</value></property>
      <property><name>gadget_reference_function</name>    <value>set_gadget_reference</value></property>
      <property><name>input_function</name>               <value>recon_function</value></property>
      <property><name>config_function</name>              <value>config_function</value></property>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>  
    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/mri_core/unified_epi.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
  
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
  
    <!--Prewhiten -->
    <gadget>
      <name>NoiseAdjust</name>
      <dll>gadgetron_mricore</dll>
      <classname>NoiseAdjustGadget</classname>
    </gadget>
  
    <!-- Grid and FT to x -->
    <gadget>
      <name>ReconX</name>
      <dll>gadgetron_epi</dll>
      <classname>EPIReconXGadget</classname>
    </gadget>

    <!-- Apply EPI corrections -->
    <gadget>
      <name>EPICorr</name>
      <dll>gadgetron_epi</dll>
      <classname>EPICorrGadget</classname>
    </gadget>

    <!-- FFT in X back to k -->
    <gadget>
        <name>FFTX</name>
        <dll>gadgetron_epi</dll>
        <classname>FFTXGadget</classname>
    </gadget>

    <!-- Accumulate and trigger
            1 bucket for each slice 
            trigger on every repetition -->
    <gadget>
        <name>AccTrig</name>
        <dll>gadgetron_mricore</dll>
	<classname>AcquisitionAccumulateTriggerGadget</classname>
        <property>
            <name>trigger_dimension</name>
            <value>repetition</value>
        </property>
        <property>
          <name>sorting_dimension</name>
          <value>slice</value>
        </property>
    </gadget>

    <!-- Convert from bucket to buffer
            1 buffer per slice -->
    <gadget>
        <name>Buff</name>
        <dll>gadgetron_mricore</dll>
	<classname>BucketToBufferGadget</classname>
        <property>
            <name>N_dimension</name>
            <value>contrast</value>
        </property>
        <property>
          <name>S_dimension</name>
          <value>phase</value>
        </property>
        <property>
          <name>split_slices</name>
          <value>true</value>
        </property>
        <property>
          <name>ignore_segment</name>
          <value>true</value>
        </property>
    </gadget>


</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/octave/octave.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
  
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>
    
    <gadget>
      <name>OctaveDownsample</name>
      <dll>gadgetron_octave</dll>
      <classname>AcquisitionOctaveGadget</classname>
      <!--
   	  <property><name>path</name>                  <value>/home/myuser/scripts/python</value></property>
      -->
      <property><name>gadget_reference_function</name>    <value>gadget_reference_downsample_2x</value></property>
      <property><name>input_function</name>               <value>downsample_2x</value></property>
      <property><name>config_function</name>              <value>configure_downsample_2x</value></property> 
    </gadget>

    <gadget>
      <name>OctaveAccumulate</name>
      <dll>gadgetron_octave</dll>
      <classname>AcquisitionOctaveGadget</classname>
      <!--
   	  <property><name>path</name>                  <value>/home/myuser/scripts/python</value></property>
      -->
      <property><name>gadget_reference_function</name>    <value>gadget_reference_accumulator</value></property>
      <property><name>input_function</name>               <value>accumulator</value></property>
      <property><name>config_function</name>              <value>configure_accumulator</value></property> 
    </gadget>

    <!--
    <gadget>
      <name>Acc</name>
      <dll>gadgetron_mricore</dll>
      <classname>AccumulatorGadget</classname>
    </gadget>

    <gadget>
      <name>FFT</name>
      <dll>gadgetron_mricore</dll>
      <classname>FFTGadget</classname>
    </gadget>

    <gadget>
      <name>CropCombine</name>
      <dll>gadgetron_mricore</dll>
      <classname>CropAndCombineGadget</classname>
    </gadget>
    -->

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
    </gadget>  
  
    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/dicom/dicom.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
    xmlns="http://gadgetron.sf.net/gadgetron"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <reader>
        <slot>1008</slot>
        <dll>gadgetron_mricore</dll>
        <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>

    <writer>
        <slot>1012</slot>
        <dll>gadgetron_dicom</dll>
        <classname>DicomImageWriter</classname>
    </writer>

    <gadget>
        <name>Acc</name>
        <dll>gadgetron_mricore</dll>
        <classname>AccumulatorGadget</classname>
    </gadget>

    <gadget>
        <name>FFT</name>
        <dll>gadgetron_mricore</dll>
        <classname>FFTGadget</classname>
    </gadget>

    <gadget>
        <name>CoilCombinePython</name>
        <dll>gadgetron_python</dll>
        <classname>ImagePythonGadget</classname>
        <property><name>python_path</name>                  <value>/home/myuser/scripts/python</value></property>
        <property><name>python_module</name>                <value>rms_coil_combine</value></property>
        <property><name>gadget_reference_function</name>    <value>set_gadget_reference</value></property>
        <property><name>input_function</name>               <value>recon_function</value></property>
        <property><name>config_function</name>              <value>config_function</value></property>
    </gadget>

    <gadget>
        <name>Extract</name>
        <dll>gadgetron_mricore</dll>
        <classname>ExtractGadget</classname>
    </gadget>

    <gadget>
        <name>AutoScale</name>
        <dll>gadgetron_mricore</dll>
        <classname>AutoScaleGadget</classname>
    </gadget>

    <gadget>
        <name>DicomFinishFLOAT</name>
        <dll>gadgetron_dicom</dll>
        <classname>DicomFinishGadgetFLOAT</classname>
    </gadget>

</gadgetronStreamConfiguration>
