=== ACampbellWashburn/gadgetron/apps/gadgetron/schema/gadgetron.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://gadgetron.sf.net/gadgetron" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gadgetron.sf.net/gadgetron">

    <!--
    Gadgetron configuration xml includes two elements: port and workingdirectory
    The 'port' is where gadgetron is listening to. This 'workingdirectory' is 
    the directory which gadgetron uses to store the temporary files, 
    e.g. the dependency measurements. If 'workingdirectory' is not set, the default
    directory will be used ('/tmp/gadgetron' in linux and 'c:/temp/gadgetron' in windows).
    -->

    <xs:element name="gadgetronConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="port" type="xs:string"/>
                <xs:element maxOccurs="1" minOccurs="0" name="workingdirectory" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

  <xs:element name="gadgetronStreamConfiguration">
    <xs:complexType>
      <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reader">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element name="slot" type="xs:unsignedShort"/>
                              <xs:element name="dll" type="xs:string"/>
                              <xs:element name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="writer">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1" name="slot" type="xs:unsignedShort"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="gadget">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1"  name="name" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                                  <xs:complexType>
                                      <xs:sequence>
                                          <xs:element maxOccurs="1" minOccurs="1" name="name" type="xs:string"/>
                                          <xs:element maxOccurs="1" minOccurs="1" name="value" type="xs:string"/>
                                      </xs:sequence>        
                                  </xs:complexType>
                              </xs:element>
                             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ACampbellWashburn/gadgetron/gadgets/mri_core/default_optimized.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_core</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>

    <writer>
      <slot>1004</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>MRINoiseAdjust</name>
      <dll>gadgetron_mricore</dll>
      <classname>MRINoiseAdjustGadget</classname>
      <!--
      <property><name>threads</name><value>2</value></property>
      -->
    </gadget>
	
    <gadget>
      <name>PCA</name>
      <dll>gadgetron_mricore</dll>
      <classname>PCACoilGadget</classname>
    </gadget>
	
    <gadget>
      <name>CoilReduction</name>
      <dll>gadgetron_core</dll>
      <classname>CoilReductionGadget</classname>
      <property><name>coils_out</name><value>16</value></property>
    </gadget>
    
    <gadget>
      <name>Acc</name>
      <dll>gadgetron_core</dll>
      <classname>AccumulatorGadget</classname>
    </gadget>
 
    <gadget>
      <name>FFT</name>
      <dll>gadgetron_core</dll>
      <classname>FFTGadget</classname>
    </gadget>

	<!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_core</dll>
      <classname>ImageWriterGadgetCPLX</classname>
    </gadget>
    -->
    
    <gadget>
      <name>CropCombine</name>
      <dll>gadgetron_core</dll>
      <classname>CropAndCombineGadget</classname>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_core</dll>
      <classname>ExtractGadget</classname>
      <!--
      <property><name>extract_mask</name><value>9</value></property>
      -->
    </gadget>

	<!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_core</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->
    
    <!--
    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_core</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
    -->
    
 	<!--
    <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetron_core</dll>
      <classname>ImageFinishGadgetCPLX</classname>
    </gadget>
    -->

    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_core</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>

    <!--
     <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetron_core</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>
    -->

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/gtPlus/config/GT_2DT_Cartesian_FirstLayer_CloudNode.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <!-- 
        GT Plus configuratin file for general 2D cartesian reconstruction using linear or non-linear SPIRIT
        The dual-layer cloud topology is used here, therefore every incoming SLICE is sent
        to one first layer GtPlus cloud node. This first layer node can further split the job and
        process the SLICE with one or more second layer nodes.

        This configuration file is for the first layer GtPlus cloud node.

        Author: Hui Xue
        Magnetic Resonance Technology Program
        National Heart, Lung and Blood Institute
        National Institutes of Health
        10 Center Drive, Bethesda
        MD 20814
        USA
        Email: hui.xue@nih.gov

        Ref to: 

        Hui Xue, Souheil Inati, Thomas Sangild Sorensen, Peter Kellman, Michael S. Hansen. 
        Distributed MRI Reconstruction using Gadgetron based Cloud Computing. 
        Magenetic Resonance in Medicine, doi: 10.1002/mrm.25213.
    -->

    <!-- reader -->
    <reader>
        <slot>1014</slot>
        <dll>gadgetronPlus</dll>
        <classname>GtPlus2DTGadgetCloudJobMessageReaderCPFL</classname>
    </reader>

    <!-- writer -->
    <writer>
        <slot>1014</slot>
        <dll>gadgetronPlus</dll>
        <classname>GtPlus2DTGadgetCloudJobMessageWriterCPFL</classname>
    </writer>

    <!--
    Recon computation for 2DT cases
    -->

    <gadget>
        <name>Recon</name>
        <dll>gadgetronPlus</dll>
        <classname>GtPlusReconJob2DTGadgetCloud</classname>

        <!-- parameters for kspace filter, image data -->
        <property>
            <name>filterRO</name>
            <value>Gaussian</value>
        </property>
        <property>
            <name>filterRO_sigma</name>
            <value>1.0</value>
        </property>
        <property>
            <name>filterRO_width</name>
            <value>0.15</value>
        </property>

        <property>
            <name>filterE1</name>
            <value>Gaussian</value>
        </property>
        <property>
            <name>filterE1_sigma</name>
            <value>1.0</value>
        </property>
        <property>
            <name>filterE1_width</name>
            <value>0.15</value>
        </property>

        <property>
            <name>filterE2</name>
            <value>Gaussian</value>
        </property>
        <property>
            <name>filterE2_sigma</name>
            <value>1.0</value>
        </property>
        <property>
            <name>filterE2_width</name>
            <value>0.15</value>
        </property>

        <!-- parameters for kspace filter, ref data -->
        <property>
            <name>filterRefRO</name>
            <value>Hanning</value>
        </property>
        <property>
            <name>filterRefRO_sigma</name>
            <value>1.5</value>
        </property>
        <property>
            <name>filterRefRO_width</name>
            <value>0.15</value>
        </property>

        <property>
            <name>filterRefE1</name>
            <value>Hanning</value>
        </property>
        <property>
            <name>filterRefE1_sigma</name>
            <value>1.5</value>
        </property>
        <property>
            <name>filterRefE1_width</name>
            <value>0.15</value>
        </property>

        <property>
            <name>filterRefE2</name>
            <value>Hanning</value>
        </property>
        <property>
            <name>filterRefE2_sigma</name>
            <value>1.5</value>
        </property>
        <property>
            <name>filterRefE2_width</name>
            <value>0.15</value>
        </property>

        <!-- parameters for kspace filter, partial fourier/asymmetric echo filter -->
        <property>
            <name>filterPartialFourierRO</name>
            <value>TaperedHanning</value>
        </property>
        <property>
            <name>filterPartialFourierRO_sigma</name>
            <value>1.5</value>
        </property>
        <property>
            <name>filterPartialFourierRO_width</name>
            <value>0.15</value>
        </property>
        <property>
            <name>filterPartialFourierRO_densityComp</name>
            <value>true</value>
        </property>

        <property>
            <name>filterPartialFourierE1</name>
            <value>TaperedHanning</value>
        </property>
        <property>
            <name>filterPartialFourierE1_sigma</name>
            <value>1.5</value>
        </property>
        <property>
            <name>filterPartialFourierE1_width</name>
            <value>0.15</value>
        </property>
        <property>
            <name>filterPartialFourierE1_densityComp</name>
            <value>true</value>
        </property>

        <property>
            <name>filterPartialFourierE2</name>
            <value>TaperedHanning</value>
        </property>
        <property>
            <name>filterPartialFourierE2_sigma</name>
            <value>1.5</value>
        </property>
        <property>
            <name>filterPartialFourierE2_width</name>
            <value>0.15</value>
        </property>
        <property>
            <name>filterPartialFourierE2_densityComp</name>
            <value>true</value>
        </property>

        <!-- parameters for recon job split -->
        <property>
            <name>job_split_by_S</name>
            <value>false</value>
        </property>
        <property>
            <name>job_num_of_N</name>
            <value>48</value>
        </property>
        <property>
            <name>job_max_Megabytes</name>
            <value>2048</value>
        </property>
        <property>
            <name>job_overlap</name>
            <value>1</value>
        </property>
        <property>
            <name>job_perform_on_control_node</name>
            <value>true</value>
        </property>

        <!-- parameters for the cloud computation 
             The cloud should be defined as the following: CloudNodeX_IP/Port/XMLConfiguration etc.
        -->
        <property><name>CloudComputing</name><value>false</value></property>
        <property><name>cloudNodeFile</name><value>myCloud_2DT_DualLayer_FirstLayer.txt</value></property>
        <property><name>CloudNodeXMLConfiguration</name><value>GT_2DT_Cartesian_CloudNode.xml</value></property>

        <!-- parameters for debug and timing -->
        <property>
            <name>debugFolder</name>
            <value></value>
        </property>

        <property>
            <name>debugFolder2</name>
            <value></value>
        </property>

        <property>
            <name>performTiming</name>
            <value>true</value>
        </property>

        <property>
            <name>verboseMode</name>
            <value>true</value>
        </property>

    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/mri_core/default_short.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_core</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
    <writer>
      <slot>1004</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_core</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>Acc</name>
      <dll>gadgetron_core</dll>
      <classname>AccumulatorGadget</classname>
    </gadget>

    <gadget>
      <name>FFT</name>
      <dll>gadgetron_core</dll>
      <classname>FFTGadget</classname>
    </gadget>

    <gadget>
      <name>CropCombine</name>
      <dll>gadgetron_core</dll>
      <classname>CropAndCombineGadget</classname>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetron_core</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetron_core</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>

    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetron_core</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
 
     <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetron_core</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/spiral/config/adrienneOffRes.xml
<?xml version="1.0" encoding="utf-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <reader>
    <slot>1008</slot>
    <dll>gadgetron_mricore</dll>
    <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
  </reader>
 
  <writer>
    <slot>1022</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriter</classname>
  </writer>
<!--  
  <writer>
    <slot>1004</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriterCPLX</classname>
  </writer>
  <writer>
    <slot>1005</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriterFLOAT</classname>
  </writer>
  <writer>
    <slot>1006</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriterUSHORT</classname>
  </writer>
-->
  <gadget>
    <name>NoiseAdjust</name>
    <dll>gadgetron_mricore</dll>
    <classname>NoiseAdjustGadget</classname>
  </gadget>
  
  <gadget>
    <name>PCA</name>
    <dll>gadgetron_mricore</dll>
    <classname>PCACoilGadget</classname>
  </gadget>
  
  <gadget>
    <name>CoilReduction</name>
    <dll>gadgetron_mricore</dll>
    <classname>CoilReductionGadget</classname>
    <property><name>coils_out</name><value>16</value></property>
  </gadget>
<!--
  <gadget>
    <name>SpiralToGenericGadget</name>
    <dll>gadgetron_spiral</dll>
    <classname>SpiralToGenericGadget</classname>
  </gadget>
-->

  <gadget>
    <name>SpiralOffResSets</name>
    <dll>gadgetron_spiral</dll>
    <classname>SpiralOffResSets</classname>
  </gadget>

  <gadget>
    <name>gpuGenericSensePrepGadgetRegrid</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuGenericSensePrepGadgetRegrid</classname>
    <!-- <property><name>deviceno</name><value>0</value></property>
    <property><name>buffer_convolution_kernel_width</name><value>4.5</value></property>
    <property><name>buffer_convolution_oversampling_factor</name><value>1.25</value></property>
-->
  </gadget>

  <gadget>
    <name>SpiralOffResSubtract</name>
    <dll>gadgetron_spiral</dll>
    <classname>SpiralOffResSubtract</classname>
  </gadget>

<!--
  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>0</value></property>
    <property><name>number_of_iterations</name>    <value>1</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>4.5</value></property>
    <property><name>kappa</name>                   <value>0.3</value></property>
  </gadget>

  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpuparallelmri</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>1</value></property>
    <property><name>number_of_iterations</name>    <value>5</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>4.5</value></property>
    <property><name>kappa</name>                   <value>0.3</value></property>
  </gadget>
-->
  <gadget>
    <name>Extract</name>
    <dll>gadgetron_mricore</dll>
    <classname>ExtractGadget</classname>
  </gadget>
  
  <!--
      <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
      </gadget>
  -->    
  
  <gadget>
    <name>AutoScaleGadget</name>
    <dll>gadgetron_mricore</dll>
    <classname>AutoScaleGadget</classname>
  </gadget> 

  <gadget>
    <name>FloatToShort</name>
    <dll>gadgetron_mricore</dll>
    <classname>FloatToUShortGadget</classname>
  </gadget>
  
  <!--
      <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetCPLX</classname>
      </gadget>
  -->
  
  <gadget>
    <name>ImageFinish</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageFinishGadget</classname>
  </gadget>    

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/sbsense/radial_single_sb.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetroncore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
    <writer>
      <slot>1004</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>NoiseAdjust</name>
      <dll>gadgetronmricore</dll>
      <classname>MRINoiseAdjustGadget</classname>
    </gadget>

    <gadget>
      <name>RemoveROOversampling</name>
      <dll>gadgetroncore</dll>
      <classname>RemoveROOversamplingGadget</classname>
    </gadget>

   <gadget>
      <name>PCA</name>
      <dll>gadgetronmricore</dll>
      <classname>PCACoilGadget</classname>
    </gadget>

    <gadget>
      <name>CoilReduction</name>
      <dll>gadgetroncore</dll>
      <classname>CoilReductionGadget</classname>
      <property>
        <name>coils_out</name>
        <value>8</value>
      </property>
    </gadget>

    <gadget>
      <name>cuSbRadial0</name>
      <dll>gadgetronsbsense</dll>
      <classname>cuSbGoldenRadialGadget</classname>
      <property><name>deviceno</name>                <value>0</value></property>
      <property><name>sliceno</name>                 <value>0</value></property>
      <property><name>profiles_per_frame</name>      <value>32</value></property>
      <property><name>shared_profiles</name>         <value>0</value></property>
      <property><name>number_of_iterations</name>    <value>10</value></property>
      <property><name>cg_limit</name>                <value>1e-4</value></property>
      <property><name>oversampling</name>            <value>1.25</value></property>
      <property><name>kernel_width</name>            <value>5.5</value></property>
      <property><name>kappa</name>                   <value>0.3</value></property>
      <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    </gadget>

     <gadget>
      <name>Extract</name>
      <dll>gadgetroncore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

	<!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetroncore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->

    <gadget>
      <name>AutoScale</name>
      <dll>gadgetroncore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget>


    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetroncore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>

    <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/python/config/python_tpat_snr_scale.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         
    <reader>
      <slot>1008</slot>
      <dll>gadgetron_mricore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>

    <writer>
      <slot>1004</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetron_mricore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>NoiseAdj</name>
      <dll>gadgetron_python</dll>
      <classname>AcquisitionPythonGadget</classname>
      <property><name>python_module</name>                <value>tpat_snr_scale</value></property>
      <property><name>python_class</name>                <value>NoiseAdj</value></property>
    </gadget>

    <gadget>
      <name>RemOS</name>
      <dll>gadgetron_python</dll>
      <classname>AcquisitionPythonGadget</classname>
      <property><name>python_module</name>                <value>tpat_snr_scale</value></property>
      <property><name>python_class</name>                <value>RemOS</value></property>
    </gadget>

    <gadget>
      <name>PCA</name>
      <dll>gadgetron_python</dll>
      <classname>AcquisitionPythonGadget</classname>
      <property><name>python_module</name>                <value>tpat_snr_scale</value></property>
      <property><name>python_class</name>                <value>PCA</value></property>
    </gadget>

    <gadget>
      <name>CoilReduce</name>
      <dll>gadgetron_python</dll>
      <classname>AcquisitionPythonGadget</classname>
      <property><name>python_module</name>                <value>tpat_snr_scale</value></property>
      <property><name>python_class</name>                <value>CoilReduce</value></property>
    </gadget>

    <gadget>
      <name>Recon</name>
      <dll>gadgetron_python</dll>
      <classname>AcquisitionPythonGadget</classname>
      <property><name>python_module</name>                <value>tpat_snr_scale</value></property>
      <property><name>python_class</name>                <value>Recon</value></property>
    </gadget>

     <gadget>
      <name>Extract</name>
      <dll>gadgetron_mricore</dll>
      <classname>ExtractGadget</classname>
     </gadget>
  
    <gadget>
      <name>ImageFinishFLOAT</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/spiral/gpu/spiral_gpusense_gp_unoptimized.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <reader>
    <slot>1008</slot>
    <dll>gadgetron_core</dll>
    <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
  </reader>
  
  <writer>
    <slot>1004</slot>
    <dll>gadgetron_core</dll>
    <classname>MRIImageWriterCPLX</classname>
  </writer>
  <writer>
    <slot>1005</slot>
    <dll>gadgetron_core</dll>
    <classname>MRIImageWriterFLOAT</classname>
  </writer>
  <writer>
    <slot>1006</slot>
    <dll>gadgetron_core</dll>
    <classname>MRIImageWriterUSHORT</classname>
  </writer>

  <gadget>
    <name>NoiseAdjust</name>
    <dll>gadgetron_core</dll>
    <classname>NoiseAdjustGadget</classname>
  </gadget>
  
  <gadget>
    <name>RemoveROOversampling</name>
    <dll>gadgetron_core</dll>
    <classname>RemoveROOversamplingGadget</classname>
  </gadget>

  <gadget>
    <name>gpuSpiralSensePrepGadget</name>
    <dll>gadgetron_gpuspiral</dll>
    <classname>gpuSpiralSensePrepGadget</classname>
    <property><name>deviceno</name><value>0</value></property>
    <property><name>use_multiframe_grouping</name><value>false</value></property>
  </gadget>
  
  <gadget>
    <name>gpuGpSenseGadget</name>
    <dll>gadgetron_gpusense</dll>
    <classname>gpuGpSenseGadget</classname>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>number_of_iterations</name>    <value>50</value></property>
    <property><name>oversampling</name>            <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>5.5</value></property>
    <property><name>lambda</name>                  <value>2.0e-7</value></property>
    <property><name>alpha</name>                   <value>0.5</value></property>
  </gadget>

  <gadget>
    <name>PhaseSubtraction</name>
    <dll>gadgetron_core</dll>
    <classname>FlowPhaseSubtractionGadget</classname>
  </gadget>
  
  <gadget>
    <name>Extract</name>
    <dll>gadgetron_core</dll>
    <classname>ExtractGadget</classname>
    <property><name>extract_mask</name><value>9</value></property>
  </gadget>
  
  <!--
      <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_core</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
      </gadget>
  -->    
  
  <gadget>
    <name>AutoScaleGadget</name>
    <dll>gadgetron_core</dll>
    <classname>AutoScaleGadget</classname>
  </gadget> 

  <gadget>
    <name>FloatToShort</name>
    <dll>gadgetron_core</dll>
    <classname>FloatToUShortGadget</classname>
  </gadget>
  
  <!--
      <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetron_core</dll>
      <classname>ImageFinishGadgetCPLX</classname>
      </gadget>
  -->
  
  <gadget>
    <name>ImageFinishShort</name>
    <dll>gadgetron_core</dll>
    <classname>ImageFinishGadgetUSHORT</classname>
  </gadget>    

</gadgetronStreamConfiguration>
