=== ACampbellWashburn/gadgetron/apps/gadgetron/schema/gadgetron.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns="http://gadgetron.sf.net/gadgetron" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gadgetron.sf.net/gadgetron">

    <!--
    Gadgetron configuration xml includes two elements: port and workingdirectory
    The 'port' is where gadgetron is listening to. This 'workingdirectory' is 
    the directory which gadgetron uses to store the temporary files, 
    e.g. the dependency measurements. If 'workingdirectory' is not set, the default
    directory will be used ('/tmp/gadgetron' in linux and 'c:/temp/gadgetron' in windows).
    -->

    <xs:element name="gadgetronConfiguration">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="port" type="xs:string"/>
                <xs:element maxOccurs="1" minOccurs="0" name="workingdirectory" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

  <xs:element name="gadgetronStreamConfiguration">
    <xs:complexType>
      <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="reader">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element name="slot" type="xs:unsignedShort"/>
                              <xs:element name="dll" type="xs:string"/>
                              <xs:element name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="writer">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1" name="slot" type="xs:unsignedShort"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                          </xs:sequence>
                      </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="gadget">
                    <xs:complexType>
                          <xs:sequence>
                              <xs:element maxOccurs="1" minOccurs="1"  name="name" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="dll" type="xs:string"/>
                              <xs:element maxOccurs="1" minOccurs="1"  name="classname" type="xs:string"/>
                              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                                  <xs:complexType>
                                      <xs:sequence>
                                          <xs:element maxOccurs="1" minOccurs="1" name="name" type="xs:string"/>
                                          <xs:element maxOccurs="1" minOccurs="1" name="value" type="xs:string"/>
                                      </xs:sequence>        
                                  </xs:complexType>
                              </xs:element>
                             </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ACampbellWashburn/gadgetron/gadgets/core/default_short.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        
    <reader>
      <slot>1008</slot>
      <dll>gadgetroncore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
    <writer>
      <slot>1004</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

    <gadget>
      <name>Acc</name>
      <dll>gadgetroncore</dll>
      <classname>AccumulatorGadget</classname>
    </gadget>

    <gadget>
      <name>FFT</name>
      <dll>gadgetroncore</dll>
      <classname>FFTGadget</classname>
    </gadget>

    <gadget>
      <name>CropCombine</name>
      <dll>gadgetroncore</dll>
      <classname>CropAndCombineGadget</classname>
    </gadget>

    <gadget>
      <name>Extract</name>
      <dll>gadgetroncore</dll>
      <classname>ExtractGadget</classname>
    </gadget>

    <gadget>
   		<name>AutoScale</name>
   		<dll>gadgetroncore</dll>
   		<classname>AutoScaleGadget</classname>
   	</gadget>

    <gadget>
      <name>FloatToShort</name>
      <dll>gadgetroncore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
 
     <gadget>
      <name>ImageFinishUSHORT</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/matlab/matlab.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
    xmlns="http://gadgetron.sf.net/gadgetron"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <reader>
        <slot>1008</slot>
        <dll>gadgetroncore</dll>
        <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>

    <writer>
        <slot>1004</slot>
        <dll>gadgetroncore</dll>
        <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
        <slot>1005</slot>
        <dll>gadgetroncore</dll>
        <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
        <slot>1006</slot>
        <dll>gadgetroncore</dll>
        <classname>MRIImageWriterUSHORT</classname>
    </writer>


<!--
    <gadget>
        <name>MatlabAcquisition</name>
        <dll>gadgetronmatlab</dll>
        <classname>AcquisitionMatlabGadget</classname>
-->
        <!--<property><name>path</name><value></value></property>-->
<!--
        <property><name>matlab_classname</name><value>scale</value></property>
    </gadget>
-->
    <!--
    <gadget>
        <name>Acc</name>
        <dll>gadgetroncore</dll>
        <classname>AccumulatorGadget</classname>
    </gadget>
    -->
    <gadget>
        <name>MatlabAcquisition</name>
        <dll>gadgetronmatlab</dll>
        <classname>AcquisitionMatlabGadget</classname>
        <property><name>matlab_classname</name><value>accumulate_and_recon</value></property>
    </gadget>
    <gadget>
      <name>FFT</name>
      <dll>gadgetroncore</dll>
      <classname>FFTGadget</classname>
    </gadget>
    <gadget>
      <name>CropCombine</name>
      <dll>gadgetroncore</dll>
      <classname>CropAndCombineGadget</classname>
    </gadget>
    <!--<gadget>
        <name>MatlabImage</name>
        <dll>gadgetronmatlab</dll>
        <classname>ImageMatlabGadget</classname>
        <property><name>matlab_classname</name><value>fft</value></property>
    </gadget>-->
    <gadget>
        <name>Extract</name>
        <dll>gadgetroncore</dll>
        <classname>ExtractGadget</classname>
    </gadget>
    <gadget>
        <name>ImageFinishFLOAT</name>
        <dll>gadgetroncore</dll>
        <classname>ImageFinishGadgetFLOAT</classname>
    </gadget>
</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/moco/config/cpu_registration_averaging_gpucg.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
			      xmlns="http://gadgetron.sf.net/gadgetron"
			      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  
  <reader>
    <slot>1008</slot>
    <dll>gadgetron_mricore</dll>
    <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
  </reader>
  
  <writer>
    <slot>1004</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriterCPLX</classname>
  </writer>
  <writer>
    <slot>1005</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriterFLOAT</classname>
  </writer>
  <writer>
    <slot>1006</slot>
    <dll>gadgetron_mricore</dll>
    <classname>MRIImageWriterUSHORT</classname>
  </writer>

  <gadget>
    <name>NoiseAdjust</name>
    <dll>gadgetron_mricore</dll>
    <classname>NoiseAdjustGadget</classname>
  </gadget>
  
  <gadget>
    <name>PCA</name>
    <dll>gadgetron_mricore</dll>
    <classname>PCACoilGadget</classname>
  </gadget>
  
  <gadget>
    <name>CoilReduction</name>
    <dll>gadgetron_mricore</dll>
    <classname>CoilReductionGadget</classname>
    <property><name>coils_out</name><value>16</value></property>
  </gadget>

  <gadget>
    <name>SpiralToGenericGadget</name>
    <dll>gadgetron_spiral</dll>
    <classname>SpiralToGenericGadget</classname>
  </gadget>

  <gadget>
    <name>gpuGenericSensePrepGadget</name>
    <dll>gadgetron_gpusense</dll>
    <classname>gpuGenericSensePrepGadget</classname>
    <property><name>deviceno</name><value>0</value></property>
    <property><name>rotations_per_reconstruction</name><value>16</value></property>
    <property><name>propagate_csm_from_set</name><value>0</value></property>
    <property><name>buffer_convolution_kernel_width</name><value>5.5</value></property>
    <property><name>buffer_convolution_oversampling_factor</name><value>1.25</value></property>
    <property><name>reconstruction_os_factor_x</name><value>1.5</value></property>
    <property><name>reconstruction_os_factor_y</name><value>1.5</value></property>
  </gadget>
  
  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpusense</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>0</value></property>
    <property><name>number_of_iterations</name>    <value>5</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>5.5</value></property>
    <property><name>kappa</name>                   <value>0.1</value></property>
    <property><name>output_convergence</name><value>true</value></property>
  </gadget>

  <gadget>
    <name>gpuCgSenseGadget</name>
    <dll>gadgetron_gpusense</dll>
    <classname>gpuCgSenseGadget</classname>
    <property><name>pass_on_undesired_data</name>  <value>true</value></property>
    <property><name>deviceno</name>                <value>0</value></property>
    <property><name>setno</name>                   <value>1</value></property>
    <property><name>number_of_iterations</name>    <value>5</value></property>
    <property><name>cg_limit</name>                <value>1e-6</value></property>
    <property><name>oversampling_factor</name>     <value>1.25</value></property>
    <property><name>kernel_width</name>            <value>5.5</value></property>
    <property><name>kappa</name>                   <value>0.1</value></property>
    <property><name>output_convergence</name><value>true</value></property>
  </gadget>

  <gadget>
    <name>PhaseSubtraction</name>
    <dll>gadgetron_mricore</dll>
    <classname>FlowPhaseSubtractionGadget</classname>
  </gadget>
  
  <gadget>
    <name>PhysioInterpolationGadget</name>
    <dll>gadgetron_mricore</dll>
    <classname>PhysioInterpolationGadget</classname>
    <property><name>mode</name><value>0</value></property>
  </gadget>

  <gadget>
    <name>Extract</name>
    <dll>gadgetron_mricore</dll>
    <classname>ExtractGadget</classname>
  </gadget>

  <gadget>
    <name>cpuRegistrationAveragingGadget2D</name>
    <dll>gadgetron_moco</dll>
    <classname>cpuRegistrationAveragingGadget2D</classname>
    <property><name>output_convergence</name><value>true</value></property>
  </gadget>

  
  <!--
      <gadget>
      <name>ImageWrite</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
      </gadget>
  -->    
  
  
  <!--
      <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetron_mricore</dll>
      <classname>ImageFinishGadgetCPLX</classname>
      </gadget>
  -->
  
  <gadget>
    <name>ImageFinishFloat</name>
    <dll>gadgetron_mricore</dll>
    <classname>ImageFinishGadgetFLOAT</classname>
  </gadget>    

</gadgetronStreamConfiguration>

=== ACampbellWashburn/gadgetron/gadgets/spiral/spiral_MSH.xml
<?xml version="1.0" encoding="UTF-8"?>
<gadgetronStreamConfiguration xsi:schemaLocation="http://gadgetron.sf.net/gadgetron gadgetron.xsd"
        xmlns="http://gadgetron.sf.net/gadgetron"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
         
    <reader>
      <slot>1008</slot>
      <dll>gadgetroncore</dll>
      <classname>GadgetIsmrmrdAcquisitionMessageReader</classname>
    </reader>
 
    <writer>
      <slot>1004</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterCPLX</classname>
    </writer>
    <writer>
      <slot>1005</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterFLOAT</classname>
    </writer>
    <writer>
      <slot>1006</slot>
      <dll>gadgetroncore</dll>
      <classname>MRIImageWriterUSHORT</classname>
    </writer>

   <gadget>
      <name>NoiseAdjust</name>
      <dll>gadgetronmricore</dll>
      <classname>MRINoiseAdjustGadget</classname>
    </gadget>
  
  	<gadget>
      <name>PCA</name>
      <dll>gadgetronmricore</dll>
      <classname>PCACoilGadget</classname>
    </gadget>
  
    <gadget>
      <name>CoilReduction</name>
      <dll>gadgetroncore</dll>
      <classname>CoilReductionGadget</classname>
      <property><name>coils_out</name><value>8</value></property>
    </gadget>

    <gadget>
      <name>SpiralGadgetSW</name>
      <dll>gadgetronspiral</dll>
      <classname>SpiralGadgetSW</classname>
      <property><name>deviceno</name>                <value>0</value></property>
    </gadget>
    
    <gadget>
      <name>GPUCGGadgetGeneric</name>
      <dll>gadgetroncgsense</dll>
      <classname>GPUCGGadgetGeneric</classname>
      <property><name>deviceno</name>                <value>1</value></property>
      <property><name>number_of_iterations</name>    <value>10</value></property>
      <property><name>cg_limit</name>                <value>1e-6</value></property>
      <property><name>oversampling</name>            <value>1.25</value></property>
      <property><name>kernel_width</name>            <value>5.5</value></property>
      <property><name>kappa</name>                   <value>0.1</value></property>
    </gadget>

	  <gadget>
      <name>PhaseSubtraction</name>
      <dll>gadgetronspiral</dll>
      <classname>FlowPhaseSubtractionGadget</classname>
      </gadget>


	  <gadget>
      <name>Extract</name>
      <dll>gadgetroncore</dll>
      <classname>ExtractGadget</classname>
      <property><name>extract_mask</name><value>9</value></property>
      </gadget>

	<!--
    <gadget>
      <name>ImageWrite</name>
      <dll>gadgetroncore</dll>
      <classname>ImageWriterGadgetFLOAT</classname>
    </gadget>
    -->    
    
    <gadget>
      <name>AutoScaleGadget</name>
      <dll>gadgetroncore</dll>
      <classname>AutoScaleGadget</classname>
    </gadget> 

   <gadget>
      <name>FloatToShort</name>
      <dll>gadgetroncore</dll>
      <classname>FloatToUShortGadget</classname>
    </gadget>
 
 	<!--
    <gadget>
      <name>ImageFinishCPLX</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetCPLX</classname>
    </gadget>
    -->
    
    <gadget>
      <name>ImageFinishShort</name>
      <dll>gadgetroncore</dll>
      <classname>ImageFinishGadgetUSHORT</classname>
    </gadget>    

</gadgetronStreamConfiguration>
